{% set name = "viztracer" %}
{% set version = "0.17.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/viztracer-{{ version }}.tar.gz
  sha256: 20397b0c2a6341513596fe4c292994c3db8f3f6b79a0a4f497dadb9d73d988b8

build:
  number: 0
  skip: true  # [py2k]
  entry_points:
    - viztracer = viztracer:main
    - vizviewer = viztracer:viewer_main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - orjson
    - objprint >=0.1.3

test:
  imports:
    - viztracer
  commands:
    - pip check
    - viztracer --help
    - vizviewer --help
  requires:
    - pip

about:
  home: https://github.com/gaogaotiantian/viztracer
  summary: A debugging and profiling tool that can trace and visualize python code execution
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gaogaotiantian
    - gforsyth
